import React, { useState, useEffect } from "react";

import { Modal, Button, Form } from "react-bootstrap";
import { useTranslation } from "react-i18next";
import { User } from "../../interfaces/userInterface";
import { userRoleList } from "../../constants/userRolesList";

interface UserFormProps {
  show: boolean;
  onHide: () => void;
  onSave: (user: User) => void;
  editingUser?: User | null;
}

const UserForm: React.FC<UserFormProps> = ({
  show,
  onHide,
  onSave,
  editingUser,
}) => {
  const { t } = useTranslation();
  const [formData, setFormData] = useState<User>({
    firstname: "",
    lastname: "",
    email: "",
    username: "",
    full_name: "",
    role: "",
    document_number: "",
    phone_number: "",
    reviews: [],
    disabled: false,
  });

  // Cargar datos si estamos editando
  useEffect(() => {
    if (editingUser) {
      setFormData(editingUser);
    } else {
      setFormData({
        firstname: "",
        lastname: "",
        email: "",
        username: "",
        full_name: "",
        role: "",
        document_number: "",
        phone_number: "",
        reviews: [],
      });
    }
  }, [editingUser]);

  const handleChange = (
    e: React.ChangeEvent<
      HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement
    >
  ) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    const autoGeneratedUsername = generateUsername(
      formData.firstname,
      formData.lastname
    );
    const autoGeneratedPassword = generatePassword();

    const userToSave: User = {
      ...formData,
      username: editingUser ? formData.username : autoGeneratedUsername,
      password: editingUser ? undefined : autoGeneratedPassword,
      full_name: `${formData.firstname} ${formData.lastname}`,
      image: null,
    };

    onSave(userToSave);
    onHide();

    setFormData({
      firstname: "",
      lastname: "",
      email: "",
      username: "",
      full_name: "",
      role: "",
      document_number: "",
      phone_number: "",
      reviews: [],
    });
  };

  return (
    <>
      <Modal show={show} onHide={onHide}>
        <Modal.Header closeButton>
          <Modal.Title>
            {editingUser ? t("users.edit") : t("users.new")}
          </Modal.Title>
        </Modal.Header>
        <Modal.Body>
          <Form onSubmit={handleSubmit}>
            <Form.Group controlId="firstname">
              <Form.Label>{t("users.firstname")}</Form.Label>
              <Form.Control
                type="text"
                name="firstname"
                value={formData.firstname}
                onChange={handleChange}
                required
              />
            </Form.Group>

            <Form.Group controlId="lastname">
              <Form.Label>{t("users.lastname")}</Form.Label>
              <Form.Control
                type="text"
                name="lastname"
                value={formData.lastname}
                onChange={handleChange}
                required
              />
            </Form.Group>

            <Form.Group>
              <Form.Label>{t("users.role")}</Form.Label>

              <Form.Select
                value={formData.role}
                name="role"
                onChange={handleChange}
                required
              >
                <option value="">{t("select")}</option>
                {userRoleList.map((role) => (
                  <option key={role.value} value={role.value}>
                    {t(role.labelKey)}
                  </option>
                ))}
              </Form.Select>
            </Form.Group>

            <Form.Group controlId="document_number">
              <Form.Label>{t("users.document")}</Form.Label>
              <Form.Control
                type="text"
                name="document_number"
                value={formData.document_number}
                onChange={handleChange}
                required
              />
            </Form.Group>

            <Form.Group controlId="document_number">
              <Form.Label>{t("users.phone")}</Form.Label>
              <Form.Control
                type="text"
                name="phone_number"
                value={formData.phone_number}
                onChange={handleChange}
                required
              />
            </Form.Group>

            <Form.Group controlId="email">
              <Form.Label>{t("users.email")}</Form.Label>
              <Form.Control
                type="email"
                name="email"
                value={formData.email}
                onChange={handleChange}
                required
              />
            </Form.Group>

            <div className="d-flex justify-content-end mt-3">
              <Button variant="secondary" onClick={onHide}>
                {t("cancel")}
              </Button>
              <Button variant="primary" type="submit" className="ms-2">
                {editingUser ? t("update") : t("save")}
              </Button>
            </div>
          </Form>
        </Modal.Body>
      </Modal>
    </>
  );
};

export default UserForm;

function generateUsername(firstname: string, lastname: string): string {
  const random = Math.floor(Math.random() * 1000);
  return `${firstname.charAt(0)}${lastname}`.toLowerCase() + random;
}

function generatePassword(length = 10): string {
  const chars =
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%&*";
  return Array.from(
    { length },
    () => chars[Math.floor(Math.random() * chars.length)]
  ).join("");
}
